# Generated by Django 5.2.3 on 2025-07-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demos',
            name='total_time_studied',
            field=models.DurationField(),
        ),
    ]
