# Generated by Django 5.2.3 on 2025-07-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='break_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='study_time',
            field=models.TimeField(),
        ),
    ]
