# Generated by Django 5.2.3 on 2025-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demos',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
