# Generated by Django 5.2.3 on 2025-07-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_studysession_break_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='break_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='study_time',
            field=models.DurationField(),
        ),
    ]
