# Generated by Django 5.2.3 on 2025-08-15 18:26

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_demos_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000, null=True)),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
